version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily