_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: Slax (Local)
features:
  app_home:
    home_tab_enabled: true
    messages_tab_enabled: false
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: Slax (Local)
    always_online: false
  shortcuts:
    - name: Help
      type: global
      callback_id: help
      description: Help
  slash_commands:
    - command: /slax
      url: https://slax.ngrok.io/slack/message
      description: Slax
      usage_hint: '"help"'
      should_escape: true
oauth_config:
  redirect_urls:
    - https://slax.ngrok.io/auth
  scopes:
    bot:
      - commands
settings:
  event_subscriptions:
    request_url: https://slax.ngrok.io/slack/message
    bot_events:
      - app_home_opened
  interactivity:
    is_enabled: true
    request_url: https://slax.ngrok.io/slack/message
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
