
name: Test

on: push

env:
  OTP_VERSION_SPEC: "26.2.4"
  ELIXIR_VERSION_SPEC: "1.16.2"
  MIX_ENV: test

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    services:
      postgres:
        env:
          PGUSER: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_HOST_AUTH_METHOD: trust
        image: postgres:15
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s
          --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 16
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}

      - name: Install Deps
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Security Check
        run: mix sobelow --private --skip --exit

      - name: Run Tests
        run: |
          mix format --check-formatted
          mix test
          