
name: Test

on: push

env:
  OTP_VERSION_SPEC: "27.3.4.17"
  ELIXIR_VERSION_SPEC: "1.18.5"
  MIX_ENV: test

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    services:
      postgres:
        env:
          PGUSER: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_HOST_AUTH_METHOD: trust
        image: postgres:18
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s
          --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 16
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}
          version-type: strict

      - name: Install Deps
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Security Check
        run: mix sobelow --private --skip --exit

      - name: Run Tests
        run: |
          mix format --check-formatted
          mix test
          
